blank_issues_enabled: true
contact_links:
  - name: Strona Droga do World Tour
    url: https://lpociask.github.io/RoadToUCI-site/
    about: Informacje o Prologu, sezonie Lipcowa Pętla 2026 i rozgrywce kapslowej.
